// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Replace these with your actual Firebase configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcgzrXUzFFeCHwvOLSqEXyRP9NVSohwgM',
    appId: '1:475875575304:web:5aaaefe7c29fab991a33bd',
    messagingSenderId: '475875575304',
    projectId: 'sarv-suvidhaen-ef66c',
    authDomain: 'sarv-suvidhaen-ef66c.firebaseapp.com',
    storageBucket: 'sarv-suvidhaen-ef66c.appspot.com',
    measurementId: 'G-GSBG78KYHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcgzrXUzFFeCHwvOLSqEXyRP9NVSohwgM',
    appId: 'YOUR_ANDROID_APP_ID_HERE',
    messagingSenderId: '475875575304',
    projectId: 'sarv-suvidhaen-ef66c',
    storageBucket: 'sarv-suvidhaen-ef66c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcgzrXUzFFeCHwvOLSqEXyRP9NVSohwgM',
    appId: 'YOUR_IOS_APP_ID_HERE',
    messagingSenderId: '475875575304',
    projectId: 'sarv-suvidhaen-ef66c',
    storageBucket: 'sarv-suvidhaen-ef66c.appspot.com',
    iosClientId: '475875575304-kit8evddc8avak9gn3jb9smqrfi9cu8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.passwordRemember',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcgzrXUzFFeCHwvOLSqEXyRP9NVSohwgM',
    appId: 'YOUR_MACOS_APP_ID_HERE',
    messagingSenderId: '475875575304',
    projectId: 'sarv-suvidhaen-ef66c',
    storageBucket: 'sarv-suvidhaen-ef66c.appspot.com',
    iosClientId: '475875575304-kit8evddc8avak9gn3jb9smqrfi9cu8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.passwordRemember',
  );
} 